export const LOGIN = 'LOGIN';
<<<<<<< HEAD
export const GET_USERS = 'GET_USERS';
export const GET_ACTIONS = 'GET_ACTIONS';
export const DELETE_ACTION = 'DELETE_ACTION';
=======
export const LOG = 'LOG';
export const GET_USERS = 'GET_USERS';
export const GET_ACTIONS = 'GET_ACTIONS';
export const DELETE_ACTION = 'DELETE_ACTION';
export const GET_ACTION_DETAIL = 'GET_ACTION_DETAIL';
export const UPDATE_ACTION = 'UPDATE_ACTION';
export const UPDATE_ACTION_ERROR = 'UPDATE_ACTION_ERROR';
>>>>>>> 10b572947c361023fc6ad32a6e16df404a3614d5
export const ADD_EXPENSE_INCOME = 'ADD_EXPENSE_INCOME'
export const GET_CATEGORIES_EXPENSE = 'GET_CATEGORIES_EXPENSE'
export const GET_CATEGORIES_INCOME = 'GET_CATEGORIES_INCOME'
export const CLEAN_USER = 'CLEAN_USER';
<<<<<<< HEAD
export const LOGIN_FAILED = 'LOGIN_FAILED';
=======
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const LOG_FAILED = 'LOG_FAILED';
>>>>>>> 10b572947c361023fc6ad32a6e16df404a3614d5
