export const LOGIN = 'LOGIN';
export const GET_USERS = 'GET_USERS';
export const GET_ACTIONS = 'GET_ACTIONS';
export const ADD_EXPENSE_INCOME = 'ADD_EXPENSE_INCOME'
export const GET_CATEGORIES_EXPENSE = 'GET_CATEGORIES_EXPENSE'
export const GET_CATEGORIES_INCOME = 'GET_CATEGORIES_INCOME'
export const CLEAN_USER = 'CLEAN_USER';
export const LOGIN_FAILED = 'LOGIN_FAILED';